name: encoder-dimensionality
dependencies:
  - python=3.7
  - pip
  - pip:
    - git+https://github.com/brain-score/brain-score
    - git+https://github.com/brain-score/model-tools
    - git+https://github.com/wktown/candidate_models
    #- git+https://github.com/BonnerLab/bonnerlab-brainscore #not needed in future (only for object2vec, not majaj)
    - jupyterlab
    - git+https://github.com/wktown/unsup_vvs.git
    #- git+https://github.com/alexsax/visual-prior.git #in .py file of home directory
    - umap-learn

variables:
  TORCH_HOME: "/data/shared/torch"
  RESULTCACHING_HOME: "/data/shared/.cache/brainscore/result-caching"
  MT_HOME: "/data/shared/.cache/brainscore/model-tools"
  BRAINIO_HOME: "/data/shared/.cache/brainscore/brainio"
  CM_HOME: "/data/shared/.cache/brainscore/candidate-models"
